"""changes in projecttask

Revision ID: 2a739bba18b3
Revises: 538bc9c4dfdd
Create Date: 2024-07-04 07:09:34.701057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a739bba18b3"
down_revision: Union[str, None] = "538bc9c4dfdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project_tasks", sa.Column("note", sa.String(length=1000), nullable=True)
    )
    op.drop_constraint(
        "project_tasks_task_note_id_fkey", "project_tasks", type_="foreignkey"
    )
    op.drop_constraint(
        "project_tasks_task_comment_id_fkey", "project_tasks", type_="foreignkey"
    )
    op.drop_column("project_tasks", "task_note_id")
    op.drop_column("project_tasks", "task_comment_id")
    op.add_column(
        "task_comments", sa.Column("project_task_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "task_comments",
        "project_tasks",
        ["project_task_id"],
        ["project_task_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_comments", type_="foreignkey")
    op.drop_column("task_comments", "project_task_id")
    op.add_column(
        "project_tasks",
        sa.Column("task_comment_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "project_tasks",
        sa.Column("task_note_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "project_tasks_task_comment_id_fkey",
        "project_tasks",
        "task_comments",
        ["task_comment_id"],
        ["comment_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "project_tasks_task_note_id_fkey",
        "project_tasks",
        "task_notes",
        ["task_note_id"],
        ["note_id"],
        ondelete="CASCADE",
    )
    op.drop_column("project_tasks", "note")
    # ### end Alembic commands ###
