"""project label changes

Revision ID: 3afa95aa1819
Revises: e18759dee88e
Create Date: 2024-06-27 07:24:53.341726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3afa95aa1819"
down_revision: Union[str, None] = "e18759dee88e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_labels", sa.Column("project_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "project_labels",
        "projects",
        ["project_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_labels", type_="foreignkey")
    op.drop_column("project_labels", "project_id")
    # ### end Alembic commands ###
