"""fixtaskissue

Revision ID: 623bf12f90b5
Revises: 7d5c1f00a514
Create Date: 2024-07-02 07:29:36.410622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "623bf12f90b5"
down_revision: Union[str, None] = "7d5c1f00a514"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "task_comments_task_id_fkey", "task_comments", type_="foreignkey"
    )
    op.drop_column("task_comments", "task_id")
    op.drop_constraint("task_notes_task_id_fkey", "task_notes", type_="foreignkey")
    op.drop_column("task_notes", "task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_notes",
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "task_notes_task_id_fkey",
        "task_notes",
        "project_tasks",
        ["task_id"],
        ["project_task_id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "task_comments",
        sa.Column("task_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "task_comments_task_id_fkey",
        "task_comments",
        "project_tasks",
        ["task_id"],
        ["project_task_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
