version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - todo-app-network
    environment:
      - DATABASE_URL=postgresql://todouser:secret@db:5432/todo
      - JWT_SECRET_KEY=secret


  db:
    image: postgres
    environment:
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - todo-app-network
    command: npm start

volumes:
  postgres_data:

networks:
  todo-app-network:
