version: "3.9"

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - todo-app-network
    environment:
      - DATABASE_URL=postgresql://todouser:secret@db:5432/todo
      - JWT_SECRET_KEY=secret


  db:
    image: postgres
    environment:
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_backend_test:/var/lib/postgresql/data
    networks:
      - todo-app-network


networks:
  todo-app-network:

volumes:
  postgres_data_backend_test: